### PR TITLE
Gabbs

### PR DESCRIPTION
**Pull request by OnlyGabs**
I changed them 
could u verify them plz?

### CODE REVIEW

**Comment by Gabbs369** [comment]
why ?

**Review by Gabbs369 — CHANGES_REQUESTED** [review]
Change the file "fixed.html"
I can't see anything

**Comment by OnlyGabs** [comment]
OK, then

**Comment by OnlyGabs** [comment]
I fixed it, could u verify plz?

**Review by Gabbs369 — APPROVED** [review]
It's okay

**Review by Gabbs369 — CHANGES_REQUESTED** [review]
Correct the file "server.py"

**Review by Gabbs369 — APPROVED** [review]
It's okay now

**Comment by Gabbs369** [comment]
It's closed this

**Pull request merged**
